version: 2

formats:
   - epub
   - pdf

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"

python:
  install:
    - method: pip
      path: .
    - requirements: requirements.txt

sphinx:
  configuration: docs/conf.py
  fail_on_warning: true
