# example_synth_config.ini

GENERAL:

  starttime: 2016-09-13 00:00:00
  endtime: 2016-09-13 00:30:00

  # name of output file containing the synthetic data set - this file format mimics the standard SRI AMISR fitted file format
  output_filename: synthetic_data.h5

  ion_mass: [16.,32.,30.,28.,14.]

  err_coef: [1.,1.e-9,5.e-9,1.e-9]

  noise: False

  summary_plot: synthetic_data_summary_risrn.png
  summary_plot_time: 2016-09-13 00:10:00


DENSITY:

  type: chapman
  N0: 4.0e+11
  H: 100000.
  z0: 300000.
  sza: 0.

VELOCITY:

  type: uniform
  value: [0., 500., 0.]

ETEMP:

  type: hypertan
  maxtemp: 4000.
  scale_height: 100000.

ITEMP:

  type: uniform
  value: 1000.


RADAR:

  # name of site
  name: Poker Flat

  # radar site coordinates (geodetic lat, lon, alt)
  site_coords: [65.13,-147.47,213.]   # PFISR
  # site_coords: [74.72955,-94.90576,145.]  # RISR-N

  # file name for the beam code table
  beamcode_filename: bcotable_pfisr.txt

  # beam codes to use
  beamcodes: [64016, 64157, 64964, 65066]

  # define slant range gates for ACFs
  range_step: 3000.
  range_start: 80000.
  range_end: 800000.

  # altitude bins for fitted data
  altbins: 100000., 150000., 200000., 250000., 300000., 350000., 400000., 450000., 500000., 550000., 600000., 650000., 700000., 750000., 800000.

  # integration period of each time step in simulated data set (this doesn't really matter)
  integration_period: 60.
